language: php

php:
  - 7.2

services:
  - mysql

install:
  - travis_retry composer install --no-interaction --prefer-source
  - mysql -e 'create database dbtest;'
  - php cli/create_tables.php

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml
after_success: bash <(curl -s https://codecov.io/bash)
